Repository PaddlePaddle/PaddleSOT, pull requests merged in 2023-07, with the labels that each got.

#229 [log] fix eval_frame_callback log err
  sot/opcode_translator/transform.py
Labels: contributor, status: proposed

#236 [Dispatcher] Supports DictVariable get and clear
  sot/opcode_translator/executor/variable_dispatch.py
  sot/opcode_translator/executor/variables/container.py
  tests/test_05_dict.py
Labels: contributor, HappyOpenSource, status: proposed

#225 [CRC] add docstring for opcode inline executor
  sot/opcode_translator/executor/opcode_inline_executor.py
Labels: contributor, HappyOpenSource, status: proposed

#259 Fix the get and pop methods for DictVariable
  sot/opcode_translator/executor/variables/container.py
  tests/test_05_dict.py
Labels: contributor, status: proposed

#234 [CRC] Adding annotations to FunctionGraph
  docs/instructions/CALL_FUNCTION.md
  sot/opcode_translator/executor/function_graph.py
Labels: contributor, HappyOpenSource, status: proposed

#255 [Dispatcher] Support more ListVariable operations
  sot/opcode_translator/executor/variable_dispatch.py
  sot/opcode_translator/executor/variables/container.py
  tests/test_04_list.py
Labels: contributor, status: proposed

#257 [Dispatcher] Support more TupleVariable operations
  sot/opcode_translator/executor/variable_dispatch.py
  sot/opcode_translator/executor/variables/container.py
  tests/test_03_tuple.py
Labels: contributor, status: proposed

#247 [CI] add Paddle Nightly build
  .github/workflows/paddle_build.yaml
  .github/workflows/paddle_ci.yaml
Labels: contributor, HappyOpenSource, status: proposed

#227 [CRC] add docstring for modify_instrs
  sot/opcode_translator/instruction_utils/instruction_utils.py
Labels: contributor, HappyOpenSource, status: proposed

#226 [CRC] add docstring for eval_frame_callback
  sot/opcode_translator/transform.py
Labels: contributor, HappyOpenSource, status: proposed

#228 [CRC] add docstring for analysis_inputs
  sot/opcode_translator/instruction_utils/opcode_analysis.py
Labels: contributor, HappyOpenSource, status: proposed

#258 [Typing] Fix some typehint and add more assert
  sot/opcode_translator/executor/mutable_data.py
  sot/opcode_translator/executor/variables/base.py
  sot/opcode_translator/executor/variables/basic.py
  sot/opcode_translator/executor/variables/callable.py
  sot/opcode_translator/executor/variables/container.py
  sot/opcode_translator/executor/variables/iter.py
Labels: contributor, status: proposed

#277 [CRC] add CompileSIRCache and FallbackWrapper
  sot/symbolic/compile_cache.py
Labels: contributor, status: proposed

#285 [SideEffect] modify assert_results_with_side_effects
  tests/test_04_list.py
  tests/test_05_dict.py
Labels: contributor

#293 [CRC] add docstring for make_guard
  sot/opcode_translator/executor/guard.py
Labels: contributor, status: proposed
