Repository PaddlePaddle/PaddleSOT, pull requests merged in 2023-08, with the labels that each got.

#296 [CRC] add docstring for some Callables
  sot/opcode_translator/executor/variables/callable.py
Labels: contributor, HappyOpenSource, status: proposed

#297 [CRC] add SymbolicTraceContext
  sot/symbolic/symbolic_context.py
Labels: contributor, status: proposed

#298 [CRC] add SIRRuntimeCache
  sot/symbolic/statement_ir.py
Labels: contributor, status: proposed

#295 [CRC] add docstring for PyCodeGen
  pyproject.toml
  sot/opcode_translator/executor/pycode_generator.py
Labels: contributor, status: proposed

#302 [CRC] add docstring for container
  sot/opcode_translator/executor/variables/container.py
Labels: contributor, status: proposed

#310 Support variable length parameters and some str method
  sot/opcode_translator/executor/dispatcher.py
  sot/opcode_translator/executor/variable_dispatch.py
  sot/opcode_translator/executor/variables/basic.py
  tests/test_20_string.py
Labels: contributor, status: proposed

#311 Add support for ceil and floor functions
  .github/workflows/paddle_ci.yaml
  sot/opcode_translator/executor/variable_dispatch.py
  tests/test_builtin_dispatch.py
Labels: contributor, status: proposed

#312 support TensorVariable unpack
  sot/opcode_translator/executor/opcode_executor.py
  tests/test_07_unpack.py
Labels: contributor, status: proposed

#313 [CRC][No.33] add docstring for Callable/Function/UDFunction
  sot/opcode_translator/executor/variables/callable.py
Labels: contributor, status: proposed

#314 [CRC][No.34] add docstring for TensorFunction/Method/Layer
  sot/opcode_translator/executor/variables/callable.py
Labels: contributor, status: proposed

#315 [CRC][No.35] add docstring for Builtin/UDGenerator
  sot/opcode_translator/executor/variables/callable.py
Labels: contributor, status: proposed

#317 add some tests
  tests/test_04_list.py
  tests/test_builtin_dispatch.py
Labels: contributor, status: proposed

#319 [Bytecode] Add MAP_ADD
  sot/opcode_translator/executor/opcode_executor.py
  tests/test_05_dict.py
Labels: contributor, status: proposed

#320 [Bytecode] support UNPACK_EX
  sot/opcode_translator/executor/opcode_executor.py
  tests/test_07_unpack.py
Labels: contributor

#318 [Dispatcher] Support `reversed(ContainerVariable)` and `list(SequenceIterVariable)`
  sot/opcode_translator/executor/variable_dispatch.py
  sot/opcode_translator/executor/variables/iter.py
  tests/test_builtin_dispatch.py
Labels: contributor, status: proposed

#326 [Dispatcher] Implement parameterless call support for list and dict
  sot/opcode_translator/executor/dispatcher.py
  sot/opcode_translator/executor/opcode_executor.py
  sot/opcode_translator/executor/variable_dispatch.py
  tests/test_04_list.py
  tests/test_05_dict.py
Labels: contributor, status: proposed

#321 [Dispatcher] Supports `pow` `sum` `ord` `chr` and ListVariable `max` `min`
  sot/opcode_translator/executor/variable_dispatch.py
  sot/opcode_translator/executor/variables/base.py
  sot/opcode_translator/executor/variables/basic.py
  sot/opcode_translator/executor/variables/container.py
  tests/test_04_list.py
  tests/test_builtin_dispatch.py
Labels: contributor, status: proposed

#327 [Dispatcher] add hasattr support for dispatcher
  sot/opcode_translator/executor/variable_dispatch.py
  sot/opcode_translator/executor/variables/base.py
  sot/opcode_translator/executor/variables/basic.py
  sot/utils/exceptions.py
  tests/test_builtin_dispatch.py
Labels: contributor, status: proposed

#332 clean from_value
  sot/opcode_translator/executor/opcode_executor.py
  sot/opcode_translator/executor/variable_dispatch.py
  sot/opcode_translator/executor/variables/base.py
  sot/opcode_translator/executor/variables/basic.py
  sot/opcode_translator/executor/variables/callable.py
  sot/opcode_translator/executor/variables/container.py
Labels: contributor, status: proposed

#278 [SideEffect] add side effects support for global
  sot/opcode_translator/executor/function_graph.py
  sot/opcode_translator/executor/mutable_data.py
  sot/opcode_translator/executor/opcode_executor.py
  sot/opcode_translator/executor/opcode_inline_executor.py
  sot/opcode_translator/executor/pycode_generator.py
  sot/opcode_translator/executor/side_effects.py
  sot/opcode_translator/executor/variables/__init__.py
  sot/opcode_translator/executor/variables/basic.py
  tests/run_all.sh
  tests/test_19_closure.py
  tests/test_21_global.py
  tests/test_case_base.py
  tests/test_exception.py
  tests/test_side_effects.py
Labels: contributor

#341 [Dispatcher] Supports `math.sqrt`
  sot/opcode_translator/executor/variable_dispatch.py
  tests/test_builtin_dispatch.py
Labels: contributor, status: proposed

#345 [refactor] unuse variables iter
  sot/opcode_translator/executor/variables/container.py
Labels: contributor

#342 [Dispatch] dict supplementary parameter calls and fix `dict.fromkeys()`
  sot/opcode_translator/executor/variable_dispatch.py
  tests/test_05_dict.py
Labels: contributor

#343 [refactor] use VariableStack instead of list
  sot/opcode_translator/executor/opcode_executor.py
  sot/opcode_translator/executor/opcode_inline_executor.py
  sot/opcode_translator/executor/variable_stack.py
  tests/test_stack.py
Labels: contributor

#346 [dispatch] support str startswith endswith
  sot/opcode_translator/executor/variable_dispatch.py
  tests/test_20_string.py
Labels: contributor

#347 [CI] Improve GitHub Actions Log info
  tests/run_all_paddle_ci.sh
Labels: contributor

#353 improve VariableStack
  sot/opcode_translator/executor/opcode_executor.py
  sot/opcode_translator/executor/variable_stack.py
Labels: contributor

#356 [opcode][3.11] support MAKE_FUNCTION in py311
  sot/opcode_translator/executor/opcode_executor.py
  tests/run_all.sh
  tests/test_04_list.py
Labels: contributor

#358 [opcode][3.11] add `BINARY_REMAINDER` and `INPLACE_REMAINDER`
  sot/opcode_translator/executor/opcode_executor.py
  tests/run_all.sh
  tests/test_14_operators.py
Labels: contributor
