Repository PaddlePaddle/PaddleSOT, pull requests merged in 2023-06, with the labels that each got.

#138 add debug_name in VariableBase
  sot/infer_meta.py
  sot/opcode_translator/executor/opcode_executor.py
  sot/opcode_translator/executor/tracker.py
  sot/opcode_translator/executor/variables/base.py
  sot/opcode_translator/executor/variables/basic.py
  sot/opcode_translator/executor/variables/callable.py
  sot/opcode_translator/executor/variables/container.py
  sot/opcode_translator/executor/variables/iter.py
Labels: contributor

#144 [opcode]`CALL_METHOD`、`LOAD_METHOD` align cpython
  sot/opcode_translator/executor/opcode_executor.py
  sot/opcode_translator/executor/variables/__init__.py
  sot/opcode_translator/executor/variables/base.py
  sot/opcode_translator/executor/variables/basic.py
  sot/opcode_translator/executor/variables/callable.py
  sot/opcode_translator/executor/variables/container.py
  sot/utils/paddle_api_config.py
  tests/test_17_paddle_layer.py
  tests/test_break_graph.py
Labels: contributor

#158 optimize `analysis_inputs`
  sot/opcode_translator/instruction_utils/opcode_analysis.py
  tests/test_analysis_inputs.py
Labels: contributor, status: proposed

#141 add error info when occur exception for simulate execution
  sot/opcode_translator/executor/opcode_executor.py
  sot/opcode_translator/executor/pycode_generator.py
  sot/utils/exceptions.py
  tests/test_exception.py
Labels: contributor

#175 [tracker viewer] colorize the trackers
  sot/opcode_translator/executor/tracker_viewer.py
Labels: contributor, HappyOpenSource, status: proposed

#173 optimize analysis_inputs
  sot/opcode_translator/instruction_utils/opcode_analysis.py
  sot/opcode_translator/instruction_utils/opcode_info.py
  tests/test_analysis_inputs.py
Labels: contributor, HappyOpenSource, status: proposed

#183 enhancing XXXVariable __repr__ simplicity
  sot/opcode_translator/executor/variables/base.py
Labels: contributor

#189 [comment] add compile_sir、need_skip_path
  sot/opcode_translator/skip_files.py
  sot/symbolic/interpreter.py
Labels: contributor, status: proposed

#193 [CRC] add docstring for `Dispatcher`
  sot/opcode_translator/executor/dispatcher.py
Labels: contributor, status: proposed

#192 [CRC] add docstring for `tracker_viewer`
  sot/opcode_translator/executor/tracker_viewer.py
Labels: contributor, status: proposed

#196 [CRC] add docstring for all trackers
  sot/opcode_translator/executor/tracker.py
Labels: contributor, status: proposed

#170 support property process in TensorVariable
  sot/infer_meta.py
  sot/opcode_translator/executor/variable_dispatch.py
  sot/opcode_translator/executor/variables/basic.py
  tests/test_18_tensor_method.py
Labels: contributor, status: proposed

#191 [CRC] add docstring for `VariableCreator`, `SpecialInferMeta` and `symbolic_translate`
  sot/infer_meta.py
  sot/translate.py
Labels: contributor, status: proposed

#198 [Dispatch] use dispatch replace `getitem`, `setitem`, `delitem` and `bool`
  sot/opcode_translator/executor/opcode_executor.py
  sot/opcode_translator/executor/variable_dispatch.py
  sot/opcode_translator/executor/variables/base.py
  sot/opcode_translator/executor/variables/basic.py
  sot/opcode_translator/executor/variables/container.py
  tests/test_03_tuple.py
  tests/test_04_list.py
  tests/test_05_dict.py
  tests/test_14_operators.py
  tests/test_15_slice.py
Labels: contributor, status: proposed

#206 [CRC] add docstring for some Variables
  sot/opcode_translator/executor/variables/base.py
  sot/opcode_translator/executor/variables/basic.py
Labels: contributor, status: proposed

#202 [CRC] add docstring for `get_instructions`
  sot/opcode_translator/instruction_utils/instruction_utils.py
Labels: contributor, HappyOpenSource, status: proposed

#211 [CRC] add docstring for StatementIR
  sot/symbolic/statement_ir.py
Labels: contributor, status: proposed

#205 [CRC] add docstring for variables/base.py
  sot/opcode_translator/executor/variables/base.py
Labels: contributor, status: proposed

#139 support closure
  sot/opcode_translator/executor/function_graph.py
  sot/opcode_translator/executor/opcode_executor.py
  sot/opcode_translator/executor/opcode_inline_executor.py
  sot/opcode_translator/executor/pycode_generator.py
  sot/opcode_translator/executor/tracker.py
  sot/opcode_translator/executor/variables/__init__.py
  sot/opcode_translator/executor/variables/basic.py
  sot/opcode_translator/executor/variables/callable.py
  tests/test_19_closure.py
Labels: contributor

#212 [CRC] add docstring for opcode executor
  sot/opcode_translator/executor/opcode_executor.py
Labels: contributor, status: proposed

#223 [CRC] add docstring for `Symbol` and `Interpreter`
  sot/symbolic/interpreter.py
  sot/symbolic/statement_ir.py
Labels: contributor, status: proposed
